name: build and deploy Carton of Tech

on:
  push:
    branches:
      - main

jobs:
  create-release:
    uses: pcarton/github-actions/.github/workflows/make-release.yaml@v0.13.0
    secrets:
      input_github_token: ${{ secrets.GITHUB_TOKEN }}

  dockerize:
    uses: pcarton/github-actions/.github/workflows/docker-to-gar.yaml@v0.13.0
    with:
      google_artifact_registry: ${{ vars.GOOGLE_ARTIFACT_REGISTRY }}
      image_name: "linkpage"
      image_tag: ${{ needs.create-release.outputs.version }}
      build_config_path: './build-config.json'
      workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      workload_identity_service_account: ${{ vars.GOOGLE_GHA_SERVICE_ACCOUNT }}
    secrets:
      input_github_token: ${{ secrets.GITHUB_TOKEN }}
    needs: [create-release]

  us-central1:
    uses: pcarton/github-actions/.github/workflows/deploy-to-cloudrun.yaml@v0.13.0
    with:
      google_region: "us-central1"
      service_name: "linkpage"
      image: ${{ needs.dockerize.outputs.image }}
      cloud_run_service_account: ${{ vars.CLOUD_RUN_SERVICE_ACCOUNT }}
      max_instances: "3"
      workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      workload_identity_service_account: ${{ vars.GOOGLE_GHA_SERVICE_ACCOUNT }}
    needs: [dockerize]
