name: Branch Validation
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v4.1.1
    - uses: rojopolis/spellcheck-github-actions@0.35.0
      name: Spellcheck
      with:
        config_path: .github/spellcheck.yml
  validate_docker_build:
    name: Validate Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4.1.1
      - name: Build Docker Image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          push: false
