name: Branch Validation
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  validate_docker_build:
    name: Validate Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4.1.1
      - name: Build Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: false
