name: Branch Validation
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test_docker_build:
    uses: pcarton/github-actions/.github/workflows/validate-docker-build.yaml@v0.12.0
    with:
      dockerfile_path: './Dockerfile'
      docker_build_context: '.'
    secrets:
      input_github_token: ${{ secrets.GITHUB_TOKEN }}
